Working for the last block
The script still has a problema of changing only the last block from
docker-compose.yml file

diff --git a/dcpr b/dcpr
--- a/dcpr
+++ b/dcpr
@@ -85,11 +85,24 @@ port_offset() {
 # main method
 dcpr () {
     if [ ! -f $1 ] || [ -z $1 ]; then
-        echo "You need to provides the first argument to be the path for docker-compose.yml file."
-        exit 1
+        if [ ! -f docker-compose.yml ]; then
+            echo "Cannot perform the task. You needs be in a folder with a docker-compose.yml file (tipically, the root from a Docker project) ot provides a docker-compose file as the first argument."
+            exit 1
+        fi
+        FILE_DOCKER=docker-compose.yml
+    else
+        FILE_DOCKER=$1
     fi
 
-    echo "Lets start this!"
+    HEADER_LINE_NUMBER=$(find_ports_starting_line $FILE_DOCKER)
+    SPAN_LINES=$(span_lines_for_ports $FILE_DOCKER)
+    for i in $(seq $SPAN_LINES); do
+        LINE_NUMBER_TARGET=$(expr $i + $HEADER_LINE_NUMBER + 1)
+        ITERATION_CONTENT=$(sed -n $LINE_NUMBER_TARGET\p $FILE_DOCKER)
+        ITERATION_CONTENT=$(echo $ITERATION_CONTENT | cut -f2 -d" ")
+        RENEWED_CONTENT=$(port_offset $ITERATION_CONTENT)
+        sed -i $LINE_NUMBER_TARGET\s/$ITERATION_CONTENT/$RENEWED_CONTENT/1 $FILE_DOCKER
+    done
 }
 
 ## detect if being sourced and
